version: '3.9'

services:
  # PostgreSQL service
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: storm_esbuild_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Elasticsearch service
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
  #   ports:
  #     - "9200:9200"
  #   environment:
  #     - discovery.type=single-node

  # Rails application service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      # - elasticsearch
  redis:
    image: redis
    ports:
      - "6379:6379"
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/0  # Use the hostname 'redis' here
    volumes:
      - .:/app
    depends_on:
      - db
      - redis


volumes:
  postgres_data: