module.exports = {
  content: [
    "./app/views/**/*.html.erb",
    "./app/helpers/**/*.rb",
    "./app/assets/stylesheets/**/*.css",
    "./app/javascript/**/*.js",
  ],
  theme: {
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1025px',
      xl: '1280px',
      '2xl': '1536px',
    },
    colors: {
      "dark-blue": "#2A343E",
      "dark-grey": "#2E3841",
      "metalic-grey": "#6E7579",
      "light-blue": "#3E4C59",
      "red": "#FF0000",
      "zinc": "#B2BDC5",
      "light-grey": "#E9E9E9",
      "yellow": "#F1C232",
      "white": "#FFFFFF",
    },
    borderColor: ({ theme }) => ({
      ...theme('colors'),
      DEFAULT: theme('colors.gray.200', 'currentColor'),
    }),
    columns: {
      auto: 'auto',
      1: '1',
      2: '2',
      3: '3',
      4: '4',
      5: '5',
      6: '6',
      7: '7',
      8: '8',
      9: '9',
      10: '10',
      11: '11',
      12: '12',
      '3xs': '16rem',
      '2xs': '18rem',
      xs: '20rem',
      sm: '24rem',
      md: '28rem',
      lg: '32rem',
      xl: '36rem',
      '2xl': '42rem',
      '3xl': '48rem',
      '4xl': '56rem',
      '5xl': '64rem',
      '6xl': '72rem',
      '7xl': '80rem',
    },
    fontFamily: {
      sans: ["Inter", "sans-serif"],
    },
  },
  plugins: [
    require("tailwind-accent-color")()
  ],
};
