# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
       
      selenium:
        image: selenium/standalone-chrome:3.141.59
        ports:
          - 4444:4444
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1.145.0 # v1.145.0
        with:
          bundler-cache: true
      # Add or replace database setup steps here

      # - name: Set up database schema
        # run: bin/rails db:schema:load
      # Add or replace test runners here

      - name: Run tests
        env:
          DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
          # REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          PG_USER: postgres
        run: |
          bin/rails test:prepare
          bin/rails db:test:prepare
          bin/rails "parallel:spec[spec\/features]"
          
      - name: Linter Check
        run: bundle exec rubocop
        # Code Climate
      - name: Setup Code Climate
        uses: amancevice/setup-code-climate@v1.1


  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@d3c9825d67b0d8720afdfdde5af56c79fdb38d16 # v1.138.0
  #       with:
  #         bundler-cache: true
